// src/constants/permissions.js
module.exports = {
    CREATE_TICKET: "CREATE_TICKET",
    VIEW_ALL_TICKETS: "VIEW_ALL_TICKETS",
    VIEW_ASSIGNED_TICKETS: "VIEW_ASSIGNED_TICKETS",
    VIEW_OWN_TICKETS: "VIEW_OWN_TICKETS",
    ASSIGN_TECHNICIAN: "ASSIGN_TECHNICIAN",
    UPDATE_STATUS: "UPDATE_STATUS",
    ADD_INTERNAL_COMMENT: "ADD_INTERNAL_COMMENT",
    ADD_PUBLIC_COMMENT: "ADD_PUBLIC_COMMENT",
    DELETE_COMMENT: "DELETE_COMMENT",
    UPLOAD_ATTACHMENT: "UPLOAD_ATTACHMENT",
    CLOSE_TICKET: "CLOSE_TICKET",
    VIEW_DASHBOARD: "VIEW_DASHBOARD",
    RATE_TECHNICIAN: "RATE_TECHNICIAN"
  };
  