// src/constants/roles.js
const P = require("./permissions");

module.exports = {
  ADMIN: [
    P.CREATE_TICKET,
    P.VIEW_ALL_TICKETS,
    P.ASSIGN_TECHNICIAN,
    P.ADD_INTERNAL_COMMENT,
    P.ADD_PUBLIC_COMMENT,
    P.UPLOAD_ATTACHMENT,
    P.CLOSE_TICKET,
    P.VIEW_DASHBOARD
  ],

  TECHNICIAN: [
    P.VIEW_ASSIGNED_TICKETS,
    P.UPDATE_STATUS,
    P.ADD_INTERNAL_COMMENT,
    P.ADD_PUBLIC_COMMENT,
    P.UPLOAD_ATTACHMENT
  ],

  CUSTOMER: [
    P.CREATE_TICKET,
    P.VIEW_OWN_TICKETS,
    P.ADD_PUBLIC_COMMENT,
    P.UPLOAD_ATTACHMENT,
    P.RATE_TECHNICIAN
  ]
};
